import Head from "next/head";
import Footer from "../components/Footer";
import Info from "../components/Info";
import Main from "../components/Main"; 
import NewsLetter from "../components/NewsLetter";
import Services from "../components/Services";
import Testimonials from "../components/Testimonials";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fyler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Main/>
        <Services/>
        <Info/>
        <Testimonials/>
        <NewsLetter/>
        <Footer/>
      </div>
        
    </div>
  );
}
